import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const quote = (value: string): string => "'" + value.replaceAll("'", "'\\''") + "'";

export function validateExample(consumer: string): void {
  const cli = (...args: string[]) =>
    spawnSync(process.execPath, ["examples/cli.js", ...args], {
      cwd: consumer,
      encoding: "utf8",
      timeout: 30_000,
    });
  for (const args of [
    ["completions"],
    ["completions", "powershell"],
    ["completions", "bash", "extra"],
    ["deploy"],
  ]) {
    const result = cli(...args);
    assert.equal(result.status, 1, `${args.join(" ")}: ${result.stderr}`);
    assert.equal(result.stdout, "");
    assert.doesNotMatch(result.stderr, /Preparing deployment/);
  }
  const help = cli("completions", "--help");
  assert.equal(help.status, 0, help.stderr);
  assert.match(help.stdout, /--executable/);
  assert.equal(help.stderr, "");
  // A token whose value is "completions" must still take the application route.
  const deploy = cli("--token", "completions", "deploy", "--target", "staging");
  assert.equal(deploy.status, 0, deploy.stderr);
  assert.equal(deploy.stdout, "Deploying to staging (example only)\n");
  assert.equal(deploy.stderr, "Preparing deployment (example only)\n");

  const directory = join(consumer, "generated");
  mkdirSync(directory);
  const shells = {
    bash: process.env.TEST_BASH ?? "/bin/bash",
    zsh: process.env.TEST_ZSH ?? "zsh",
    fish: process.env.TEST_FISH ?? "fish",
  };
  for (const shell of ["bash", "zsh", "fish"] as const) {
    const result = cli("completions", shell);
    assert.equal(result.status, 0, result.stderr);
    assert.equal(result.stderr, "", "Generation must not run the application hook");
    assert.match(result.stdout, /^# Generated by commander-static-completion/m);
    const buildTime = spawnSync(process.execPath, ["examples/generate.js", shell], {
      cwd: consumer,
      encoding: "utf8",
      timeout: 30_000,
    });
    assert.equal(buildTime.status, 0, buildTime.stderr);
    assert.equal(buildTime.stderr, "");
    assert.equal(buildTime.stdout, result.stdout, "Build-time and CLI generation must agree");
    const override = cli("completions", shell, "--executable", "mycli-preview");
    assert.equal(override.status, 0, override.stderr);
    assert.equal(override.stderr, "");
    assert.match(override.stdout, /mycli-preview/);
    const path = join(directory, shell === "zsh" ? "_mycli" : `mycli.${shell}`);
    writeFileSync(path, result.stdout);
    const syntax = spawnSync(shells[shell], ["-n", path], { encoding: "utf8", timeout: 30_000 });
    assert.equal(syntax.status, 0, syntax.stderr);

    let input: string;
    if (shell === "bash") {
      const name = result.stdout.match(/complete .*?-F (\w+)/)?.[1];
      assert.ok(name);
      input = `source ${quote(path)}\nmycli() { echo 'CLI invoked' >&2; }\nPATH=/nonexistent\nCOMP_WORDS=(mycli deploy --target pr)\nCOMP_CWORD=3\n${name}\nprintf '%s\\n' "\${COMPREPLY[@]}"\n`;
    } else if (shell === "zsh") {
      input = `fpath=(${quote(directory)} "\${fpath[@]}")\nautoload -Uz compinit\ncompinit -D -u\nmycli() { echo 'CLI invoked' >&2; }\nPATH=/nonexistent\ncompadd() { while [[ $1 != -- ]]; do shift; done; shift; printf '%s\\n' "$@"; }\nwords=(mycli deploy --target pr)\nCURRENT=4\nPREFIX=pr\n"\${_comps[mycli]}"\n`;
    } else {
      // Fish finds the installed mycli.fish by name without explicitly sourcing it.
      input = `set -g fish_complete_path ${quote(directory)}\nfunction mycli; echo 'CLI invoked' >&2; end\nset -gx PATH /nonexistent\ncomplete -C 'mycli deploy --target pr'\n`;
    }
    const loaded = spawnSync(
      shells[shell],
      shell === "bash" ? ["--noprofile", "--norc"] : shell === "zsh" ? ["-f"] : ["--no-config"],
      {
        cwd: consumer,
        input,
        encoding: "utf8",
        timeout: 30_000,
      },
    );
    assert.equal(loaded.status, 0, `${shell}: ${loaded.stderr}`);
    assert.equal(loaded.stderr, "", `${shell}: no CLI or external command should run`);
    assert.equal(loaded.stdout.trim(), "production", `${shell}: installed completion`);
  }
}
