import { readFileSync } from 'node:fs';

function quote(value) {
  if (value.includes('\0')) throw new TypeError('Shell completion strings cannot contain NUL.');
  return "'" + value.replaceAll("'", "'\\''") + "'";
}
const array = values => `(${values.map(quote).join(' ')})`;

export function renderBash(nodes, executable, prefix) {
  const specs = [];
  const spec = value => { specs.push(value); return specs.length - 1; };
  const optionCases = [], argumentCases = [], childCases = [], suggestionCases = [];
  for (const node of nodes) {
    for (const option of node.options) {
      const id = spec(option.value);
      for (const flag of option.flags) optionCases.push(`${quote(`${node.id}:${flag}`)}) mode=${option.mode}; value=${id}; variadic=${option.variadic ? 1 : 0} ;;`);
    }
    node.arguments.forEach((arg, index) => {
      argumentCases.push(`${quote(`${node.id}:${index}`)}) value=${spec(arg.value)}; variadic=${arg.variadic ? 1 : 0} ;;`);
    });
    for (const child of node.children) {
      for (const name of child.names) childCases.push(`${quote(`${node.id}:${name}`)}) next=${child.id} ;;`);
    }
    suggestionCases.push(`${node.id}) candidates=${array(node.children.filter(c => c.visible).flatMap(c => c.names))}; flags=${array([...new Set(node.options.filter(o => o.visible).flatMap(o => o.flags))])} ;;`);
  }
  const functions = [
    `${prefix}_option() {\n mode=; value=-1; variadic=0\n case "$state:$1" in\n${optionCases.join('\n')}\n esac\n}`,
    `${prefix}_argument() {\n value=-1; variadic=0\n case "$state:$position" in\n${argumentCases.join('\n')}\n esac\n}`,
    `${prefix}_child() {\n next=\n case "$state:$1" in\n${childCases.join('\n')}\n esac\n}`,
    `${prefix}_suggestions() {\n candidates=(); flags=()\n case "$state" in\n${suggestionCases.join('\n')}\n esac\n}`,
    `${prefix}_values() {\n candidates=(); kind=none\n case "$value" in\n${specs.map((s, i) => `${i}) kind=${s.kind}; candidates=${array(s.kind === 'choices' ? s.values : [])} ;;`).join('\n')}\n esac\n}`,
  ];
  const runtime = readFileSync(new URL('./runtime.bash', import.meta.url), 'utf8').replaceAll('__PREFIX__', prefix);
  return `# Generated by commander-static-completion. Requires Bash 3.2+.\n${functions.join('\n\n')}\n\n${runtime}\ncomplete -F ${prefix} -- ${quote(executable)}\n`;
}
