import type { ModelCommand } from "./model.js";
import type { CompletionHint } from "./types.js";
import { bourneRuntime } from "./bourne-runtime.js";

export function quote(value: string): string {
  if (value.includes("\0")) throw new TypeError("Shell completion strings cannot contain NUL.");
  return "'" + value.replaceAll("'", "'\\''") + "'";
}
const array = (values: readonly string[]): string => `(${values.map(quote).join(" ")})`;

export function renderBourne(
  nodes: ModelCommand[],
  executable: string,
  prefix: string,
  shell: "bash" | "zsh",
): string {
  // Zsh candidates carry a description ID until the final matching step. This
  // preserves each candidate's description across default-command alternatives.
  const descriptions: string[] = [];
  const described = (words: readonly string[], description: string): string[] => {
    if (shell === "bash") return [...words];
    let id = descriptions.indexOf(description);
    if (id < 0) {
      id = descriptions.length;
      descriptions.push(description);
    }
    return words.map((word) => `${id}:${word}`);
  };
  const specs: { hint: CompletionHint; description: string }[] = [];
  const spec = (hint: CompletionHint, description: string): number => {
    specs.push({ hint, description });
    return specs.length - 1;
  };
  const localCases: string[] = [];
  const optionCases: string[] = [],
    argumentCases: string[] = [],
    childCases: string[] = [],
    suggestionCases: string[] = [];
  for (const node of nodes) {
    for (const option of node.options) {
      const id = spec(option.value, option.description);
      for (const flag of option.flags)
        optionCases.push(
          `${quote(`${node.id}:${flag}`)}) mode=${option.mode}; combine=${option.combineOptional ? 1 : 0}; value=${id}; variadic=${option.variadic ? 1 : 0} ;;`,
        );
    }
    for (const option of node.localOptions) {
      const id = spec(option.value, option.description);
      for (const flag of option.flags)
        localCases.push(
          `${quote(`${node.id}:${flag}`)}) mode=${option.mode}; combine=${option.combineOptional ? 1 : 0}; value=${id}; variadic=${option.variadic ? 1 : 0} ;;`,
        );
    }
    node.arguments.forEach((arg, index) => {
      argumentCases.push(
        `${quote(`${node.id}:${index}`)}) value=${spec(arg.value, arg.description)}; variadic=${arg.variadic ? 1 : 0} ;;`,
      );
    });
    for (const child of node.children) {
      for (const name of child.names)
        childCases.push(`${quote(`${node.id}:${name}`)}) next=${child.id} ;;`);
    }
    suggestionCases.push(
      `${node.id}) candidates=${array(node.children.filter((c) => c.visible).flatMap((c) => described(c.names, c.description)))}; flags=${array([...new Set(node.options.filter((o) => o.visible).flatMap((o) => described(o.flags, o.description)))])} ;;`,
    );
  }
  const functions = [
    `${prefix}_settings() {\n case "$state" in\n${nodes.map((node) => `${node.id}) passthrough=${node.passThrough ? 1 : 0}; positional=${node.positional ? 1 : 0}; negative=${node.negativeNumbers ? 1 : 0}; default_command=${node.defaultCommand} ;;`).join("\n")}\n esac\n}`,
    `${prefix}_local_option() {\n mode=; value=-1; variadic=0\n case "$state:$1" in\n${localCases.join("\n")}\n esac\n}`,
    `${prefix}_option() {\n mode=; value=-1; variadic=0\n case "$state:$1" in\n${optionCases.join("\n")}\n esac\n}`,
    `${prefix}_argument() {\n value=-1; variadic=0\n case "$state:$position" in\n${argumentCases.join("\n")}\n esac\n}`,
    `${prefix}_child() {\n next=\n case "$state:$1" in\n${childCases.join("\n")}\n esac\n}`,
    `${prefix}_suggestions() {\n candidates=(); flags=()\n case "$state" in\n${suggestionCases.join("\n")}\n esac\n}`,
    `${prefix}_values() {\n candidates=(); kind=none\n case "$value" in\n${specs.map((s, i) => `${i}) kind=${s.hint.kind}; candidates=${array(described(s.hint.kind === "choices" ? s.hint.values : [], s.description))} ;;`).join("\n")}\n esac\n}`,
  ];
  if (shell === "zsh") {
    functions.push(
      `${prefix}_description() {\n description=\n case "$1" in\n${descriptions.map((text, id) => `${id}) description=${quote(text)} ;;`).join("\n")}\n esac\n}`,
    );
  }
  const runtime = bourneRuntime(shell).replaceAll("__PREFIX__", prefix);
  const registration =
    shell === "bash"
      ? `complete -o filenames -F ${prefix} -- ${quote(executable)}`
      : `# Autoload executes this file as a function; sourcing only registers it.
if [[ $ZSH_EVAL_CONTEXT == *:shfunc || $ZSH_EVAL_CONTEXT == *:loadautofunc ]]; then
  ${prefix} "$@"
else
  compdef ${prefix} ${quote(executable)}
fi`;
  // compinit reads whitespace-delimited names, not shell-quoted strings.
  const header = shell === "zsh" ? `#compdef ${executable}\n` : "";
  return `${header}# Generated by commander-static-completion. Requires ${shell === "bash" ? "Bash 3.2+" : "Zsh with compinit loaded"}.\n${functions.join("\n\n")}\n\n${runtime}\n${registration}\n`;
}
