import type { ModelCommand } from "./model.js";
import type { CompletionHint } from "./types.js";
import { fishRuntime } from "./fish-runtime.js";

function quote(value: string): string {
  // Fish represents candidates as lines with an optional tab-delimited description.
  if (/[\0\r\n\t]/u.test(value)) {
    throw new TypeError("Fish completion strings cannot contain NUL, tabs, or newlines.");
  }
  return "'" + value.replaceAll("\\", "\\\\").replaceAll("'", "\\'") + "'";
}

const print = (values: readonly string[]): string =>
  values.length ? `printf '%s\\n' ${values.map(quote).join(" ")}` : "return 0";

// Fish's switch patterns cannot reliably represent combinations of backslashes
// and wildcards. Compare user-supplied keys with literal string equality.
const literalCase = (key: string, values: readonly string[]): string =>
  `if test "$argv[1]:$argv[2]" = ${quote(key)}\n ${print(values)}\n return 0\n end`;

export function renderFish(nodes: ModelCommand[], executable: string, prefix: string): string {
  const specs: { hint: CompletionHint; description: string }[] = [];
  const spec = (hint: CompletionHint, description: string): number => {
    specs.push({ hint, description });
    return specs.length - 1;
  };
  const described = (words: readonly string[], description: string): string =>
    words
      .map((word) =>
        description ? `printf '%s\\t%s\\n' ${quote(word)} ${quote(description)}` : print([word]),
      )
      .join("\n ") || "return 0";
  const localCases: string[] = [];
  const optionCases: string[] = [],
    argumentCases: string[] = [],
    childCases: string[] = [];
  const commandCases: string[] = [],
    flagCases: string[] = [];
  for (const node of nodes) {
    for (const option of node.options) {
      const value = spec(option.value, option.description);
      for (const flag of option.flags) {
        optionCases.push(
          literalCase(`${node.id}:${flag}`, [
            option.mode,
            String(value),
            option.variadic ? "1" : "0",
            option.combineOptional ? "1" : "0",
          ]),
        );
      }
    }
    for (const option of node.localOptions) {
      const value = spec(option.value, option.description);
      for (const flag of option.flags)
        localCases.push(
          literalCase(`${node.id}:${flag}`, [
            option.mode,
            String(value),
            option.variadic ? "1" : "0",
            option.combineOptional ? "1" : "0",
          ]),
        );
    }
    node.arguments.forEach((arg, index) => {
      argumentCases.push(
        `case ${quote(`${node.id}:${index}`)}\n ${print([String(spec(arg.value, arg.description)), arg.variadic ? "1" : "0"])}`,
      );
    });
    for (const child of node.children) {
      for (const name of child.names)
        childCases.push(literalCase(`${node.id}:${name}`, [String(child.id)]));
    }
    commandCases.push(
      `case ${node.id}\n ${
        node.children
          .filter((c) => c.visible)
          .map((c) => described(c.names, c.description))
          .join("\n ") || "return 0"
      }`,
    );
    flagCases.push(
      `case ${node.id}\n ${
        node.options
          .filter((o) => o.visible && o.flags.length > 0)
          .map((o) => described(o.flags, o.description))
          .join("\n ") || "return 0"
      }`,
    );
  }
  const helper = (
    name: string,
    key: string,
    cases: string[],
    fallback: readonly string[] = [],
  ): string =>
    `function ${prefix}_${name}\n switch "${key}"\n ${cases.join("\n ")}\n case '*'\n ${print(fallback)}\n end\nend`;
  const literalHelper = (name: string, cases: string[], fallback: readonly string[]): string =>
    `function ${prefix}_${name}\n ${cases.join("\n ")}\n ${print(fallback)}\nend`;
  const functions = [
    helper(
      "settings",
      "$argv[1]",
      nodes.map(
        (node) =>
          `case ${node.id}\n ${print([node.passThrough ? "1" : "0", node.negativeNumbers ? "1" : "0", node.positional ? "1" : "0", String(node.defaultCommand)])}`,
      ),
    ),
    literalHelper("local_option", localCases, ["unknown", "-1", "0"]),
    literalHelper("option", optionCases, ["unknown", "-1", "0"]),
    helper("argument", "$argv[1]:$argv[2]", argumentCases, ["-1", "0"]),
    literalHelper("child", childCases, ["-1"]),
    helper("commands", "$argv[1]", commandCases),
    helper("flags", "$argv[1]", flagCases),
    helper(
      "values",
      "$argv[1]",
      specs.map(
        (s, i) =>
          `case ${i}\n ${described(s.hint.kind === "choices" ? s.hint.values : [], s.description)}`,
      ),
    ),
    helper(
      "kind",
      "$argv[1]",
      specs.map((s, i) => `case ${i}\n ${print([s.hint.kind])}`),
      ["none"],
    ),
  ];
  // The positional command is literal. -c parses another layer of shell syntax
  // and interprets wildcard patterns, even when its argument is quoted.
  return `# Generated by commander-static-completion. Requires Fish 4+.\n${functions.join("\n\n")}\n${fishRuntime.replaceAll("__PREFIX__", prefix)}\n# Replace this command's registration; leave other commands untouched.\ncomplete -e -- ${quote(executable)}\ncomplete -f -k -a '(${prefix})' -- ${quote(executable)}\n`;
}
